
`define JPC_ADDRESS_WIDTH 32
`define JPC_ENDIANNESS "LITTLE"
`define JPC_INSTRUCTION_WIDTH 32
`define JPC_INSTRUCTION_SIZE 4

`define JPC_MEMADDR_WIDTH 32
`define JPC_MEMDATA_WIDTH 32

`define JPC_NULL_ADDRESS {`JPC_ADDRESS_WIDTH{1'b0}}
`define JPC_NULL_DATA {`JPC_MEMDATA_WIDTH{1'b0}}

`define JPC_MEM_DEFAULT_VALUE 32'hDEADBEEF

`define JPC_REGDATA_WIDTH 32
