name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Sphinx Docs"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

